### ISSUE TITLE
Uplink not scheduled because TxRx pending

### ISSUE THREAD

**Issue by alexinthis** [lnlp/LMIC-node#24]
Hi,

I am trying to use this code on the Helium network and have made the lease amount of modifications possible to get this to work. 

I am able to receive the first transmit and after that it just says: "UL not scheduled" on the OLED or "Uplink not scheduled because TxRx pending" in the serial output.

My hardware is a ttgo_lora32_v2, and I am in Australia so have "-D CFG_au915=1" uncommented. My keys must be ok as I am receiving Join and Accept messages plus the first data message. 

If I had to guess the first send never completes correctly. 
I would normally use TTN but there is no gateway near me and someone has one setup on Helium. I don't really have the budget to purchase a gateway for either. 

Here is an output of my serial monitor with debugging on level 1

> LMIC-node
> 
> Device-id:     ttgo-lora32-v2
> LMIC library:  MCCI
> Activation:    OTAA
> LMIC debug:    1
> Interval:      60 seconds
> 
> RXMODE_RSSI
> 000000027652:  Event: EV_JOINING
> 29586: engineUpdate, opmode=0x4
> 000000029648:  Event: EV_TXSTART
> 31638: TXMODE, freq=917000000, len=23, SF=10, BW=125, CR=4/5, IH=0
> 
> 000000031666:  doWork job started
> start single rx: now-rxtime: 2
> 367198: RXMODE_SINGLE, freq=923900000, SF=10, BW=500, CR=4/5, IH=0
> 000000372607:  Event: EV_JOINED
>                Network Id: xxxxxx
>                Device Address: xxxxxx
>                Application Session Key: xxxxxxxx
>                Network Session Key:     xxxxxxxx
> 375436: engineUpdate, opmode=0x800
> 
> 000003781666:  doWork job started
> 000003784801:  Input data collected
>                COUNTER value: 1
> 000003785637:  Packet queued
> 3787745: engineUpdate, opmode=0x808
> 000003787794:  Event: EV_TXSTART
> 3789870: TXMODE, freq=917200000, len=15, SF=10, BW=125, CR=4/5, IH=0
> start single rx: now-rxtime: 2
> 3872869: RXMODE_SINGLE, freq=924500000, SF=10, BW=500, CR=4/5, IH=0
> 
> 000007531666:  doWork job started
> 000007534801:  Input data collected
>                COUNTER value: 2
> 000007534801:  Uplink not scheduled because TxRx pending
> 
> 000011281666:  doWork job started
> 000011284801:  Input data collected
>                COUNTER value: 3
> 000011284801:  Uplink not scheduled because TxRx pending

**Comment by alexinthis** [comment]
For anyone reading this who has my same issue you do in fact need to solder the DIO1 pin to GPIO33. It's working after making this change.

This link has the pin mapping you'll need
https://github.com/LilyGO/TTGO-LORA32/issues/3

**Comment by lnlp** [comment]
@alexinthis 

What you describe is already **perfectly documented** in LMIC-node's [README.md](https://github.com/lnlp/LMIC-node#21-lora-development-boards) and in the board's BSF file [`bsf_ttgo_lora32_v2.h`](https://github.com/lnlp/LMIC-node/blob/38b1804062cd272a31f50de4ba474bfbfcae8155/src/boards/bsf_ttgo_lora32_v2.h#L17)!

> This link has the pin mapping you'll need
> [LilyGO/TTGO-LORA32#3](https://github.com/LilyGO/TTGO-LORA32/issues/3)

No, that is not where anyone should look for pin mappings because everything is already contained and documented in LMIC-node.

A _newer_ version of the pin-mapping document for the TTGO LoRa32 V2.0 can be found in my [pinout-diagrams](https://github.com/lnlp/pinout-diagrams) repository, which is also (clearly) mentioned in LMIC-node's README.md.

So next time better RTFM first!! 😉
