### ISSUE TITLE
Support for Dragino Arduino Uno + Dragino LoRa-shield (BSF?)

### ISSUE THREAD

**Issue by tjeerdnet** [lnlp/LMIC-node#52]
A few weeks ago I bought a The Things Network Gateway (v3), because my Dragino Arduino Uno + Dragino LoRa-shield didn't work anymore since TTN v2 is not supported anymore. My Dragino was programmed as single channel device and it seems that was not conform to the latest standards The Things Network requires (multichannel etc.).

So I found the LMIC-node site and installed platform.io and I can upload simple code to let the LEDs blink on my Arduino. That's working.

Then I added the LMIC-node library (can be seen in this thread on [https://www.thethingsnetwork.org/forum/t/starting-out-with-an-arduino-uno-and-dragino-lora-shield/55895](https://www.thethingsnetwork.org/forum/t/starting-out-with-an-arduino-uno-and-dragino-lora-shield/55895), last comment). I fixed the SPI.h error in the meanwhile.

Now my main issue is that I need to give it a BSF (Board Support File) configuration, which I can see examples for other boards, but I have no clue what BSF I need for my Dragino Arduino Uno board. Is it possible at all to get it working on my board? I find it very hard to almost impossible to find information or examples. I also contacted the seller of my board who is in contact with Dragino, but till now no response/solution.

**Comment by lnlp** [comment]
Hi,
You will likely need to customize an existing BSF or create your own from an existing one.
I don't know your exact hardware but board_id pro8mhzatmega328 will probably come most close.
You will need to change the board (see boards supported by PlatformIO) however because your Uno will probably be 16Mhz instead of 8MHz ATmega328 and possibly use different pin definitions.

I hope this will help bit. For further questions and help please visit The Things Network Forum.
